############# English navigation ##############

# main menu
[[main]]
name = "About"
url = "/about"
weight = 1

[[main]]
weight = 9
parent = "About"
name = "About Us"
url = "/about"

[[main]]
weight = 10
parent = "About"
name = "News"
url = "/news"

[[main]]
name = "Submissions"
url = "/call-for-papers"
weight = 2

[[main]]
weight = 3
name = "Conference Venue"
url = "/venue"

[[main]]
weight = 4
name = "Program & Events"

[[main]]
weight = 21
parent = "Program & Events"
name = "Program"
url = "/program"

[[main]]
weight = 22
parent = "Program & Events"
name = "Excursion"
url = "/program/excursion"

[[main]]
weight = 5
name = "Visitor Information"


[[main]]
weight = 11
parent = "Visitor Information"
name = "About Hiroshima"
url = "/visitor/hiroshima"

[[main]]
weight = 12
parent = "Visitor Information"
name = "Accommodation"
url = "/visitor/accommodation"

[[main]]
weight = 13
parent = "Visitor Information"
name = "Important Dates"
url = "visitor/dates"


# footer menu
[[footer]]
name = "Contact"
url = "/contact"
weight = 1

[[footer]]
name = "About"
url = "/about"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 3
